# Train Test Split

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

## Load engineered training data

In [2]:
train = pd.read_csv("../data/processed/engineered_train.csv")

print("Engineered train shape:", train.shape)
train.head()

Engineered train shape: (1460, 253)

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,SalePrice,SalePrice_Log
0,60,65.0,8450,7,5,2003,2003,196.0,706.0,0.0,...,False,False,True,False,False,False,True,False,208500,12.247699
1,20,80.0,9600,6,8,1976,1976,0.0,978.0,0.0,...,False,False,True,False,False,False,True,False,181500,12.109016
2,60,68.0,11250,7,5,2001,2002,162.0,486.0,0.0,...,False,False,True,False,False,False,True,False,223500,12.317171
3,70,60.0,9550,7,5,1915,1970,0.0,216.0,0.0,...,False,False,True,False,False,False,False,False,140000,11.849405
4,60,84.0,14260,8,5,2000,2000,350.0,655.0,0.0,...,False,False,True,False,False,False,True,False,250000,12.429220

## Define features and target

In [3]:
target_original = "SalePrice"
target_log = "SalePrice_Log"

X = train.drop(columns=[target_original, target_log])
y = train[target_log]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (1460, 251)
y shape: (1460,)

## Train-validation split

We use validation data to test model performance before final prediction.

In [4]:
X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train shape:", X_train.shape)
print("X_valid shape:", X_valid.shape)
print("y_train shape:", y_train.shape)
print("y_valid shape:", y_valid.shape)

X_train shape: (1168, 251)
X_valid shape: (292, 251)
y_train shape: (1168,)
y_valid shape: (292,)

## Feature scaling

In [5]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)

X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_valid_scaled = pd.DataFrame(X_valid_scaled, columns=X_valid.columns, index=X_valid.index)

X_train_scaled.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
254,-0.866764,0.004077,-0.212896,-0.820445,0.372217,-0.455469,-1.346063,-0.597889,1.037269,-0.285504,...,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.46002,-0.302636
1066,0.074110,-0.485417,-0.265245,-0.088934,1.268609,0.718609,0.439214,-0.597889,-0.971996,-0.285504,...,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.46002,-0.302636
638,-0.631546,-0.129422,-0.177841,-0.820445,1.268609,-1.988293,-1.683818,-0.597889,-0.971996,-0.285504,...,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.46002,-0.302636
799,-0.161109,-0.440918,-0.324474,-0.820445,1.268609,-1.107734,-1.683818,0.861522,0.267995,-0.285504,...,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.46002,-0.302636
380,-0.161109,-0.885912,-0.529035,-0.820445,0.372217,-1.531707,-1.683818,-0.597889,-0.496920,-0.285504,...,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.46002,-0.302636

## Save final processed files

In [6]:
Path("../data/processed").mkdir(parents=True, exist_ok=True)

X_train.to_csv("../data/processed/X_train.csv", index=False)
X_valid.to_csv("../data/processed/X_valid.csv", index=False)
y_train.to_csv("../data/processed/y_train.csv", index=False)
y_valid.to_csv("../data/processed/y_valid.csv", index=False)

X_train_scaled.to_csv("../data/processed/X_train_scaled.csv", index=False)
X_valid_scaled.to_csv("../data/processed/X_valid_scaled.csv", index=False)

print("Final processed files saved successfully.")

Final processed files saved successfully.

In [7]:
test = pd.read_csv("../data/processed/engineered_test.csv")

test.to_csv("../data/processed/final_test.csv", index=False)

print("Final test data saved successfully.")
print("Final test shape:", test.shape)

Final test data saved successfully.
Final test shape: (1459, 251)